[package]
name = "simple-hot-on-the-heels-notebook"
version = "61.0.0"
description = "Заметки занятий для педагога"
authors = ["Ключенко М.А. <misha.klyuchenko@gmail.com>"]
license = "MIT"
edition = "2021"

[lib]
name = "simple_hot_on_the_heels_notebook_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
dirs = "5"
chrono = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-notification = "2"
