[package]
name = "simple-hot-on-the-heels-notebook"
version = "0.1.0"
description = "Дневник занятий для педагога"
authors = ["Ключенко М.А. <misha.klyuchenko@gmail.com>"]
license = "MIT"
edition = "2021"

[lib]
name = "simple_hot_on_the_heels_notebook_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
